Rebuild SYNCQT header files
ubports/qtwebengine-opensource-src-packaging pull request #7
Opened 2018-11-04 01:42 UTC by UniversalSuperBox

As suggested by @mitya57, rebuild the SYNCQT headers (the CamelCased ones) prior to the build of QtWebEngine.

Fixes #6!

2018-11-07 06:30 UTC, mitya57 requested changes

2018-11-07 06:30 UTC, mitya57 commented on debian/rules
>  	/usr/lib/$(DEB_HOST_MULTIARCH)/qt5/bin/syncqt.pl -version 5.11.2
You may want to replace hard-coded `5.11.2` with something like `$(DEB_VERSION_UPSTREAM:+dfsg=)`.

2018-11-08 17:46 UTC, delijati commented
can this be merged i'm blocked with working on `dekko2`. i'm using `bionic` to develop (desktop)

2018-11-09 18:19 UTC, UniversalSuperBox commented
@delijati, as always, if you would like to test changes in a PR, try out `ubports-qa`! This PR can be installed using `sudo ubports-qa install qtwebengine-opensource-src-packaging 7`.

2018-11-09 18:48 UTC, delijati commented
@UniversalSuperBox Hi thanks i wasn't aware of `ubports-qa`. When running i get this error:

```
% sudo ubports-qa install qtwebengine-opensource-src-packaging 7
CRITICAL:ubports-qa:Jenkins build not found

# and also with the jenkins build #
% sudo ubports-qa install qtwebengine-opensource-src-packaging 4
CRITICAL:ubports-qa:Jenkins build not found
```

2018-11-09 19:26 UTC, merged